import {
  CommandInteraction,
  Client,
  TextChannel,
  MessageFlags,
  DMChannel,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  ButtonInteraction,
} from "discord.js";
import { Command } from "../Command";
import * as fs from "fs";
import * as path from "path";

const ADMIN_CHANNEL_ID = "1391277749695549583";

// Theme keywords for tagging (TikTok/brainrot humor)
const THEME_KEYWORDS = {
  sigma: [
    "sigma",
    "alpha",
    "beta",
    "grindset",
    "gigachad",
    "chad",
    "based",
    "cringe",
    "sigma male",
    "alpha male",
    "ohio",
    "W",
    "L",
    "ratio",
    "mog",
    "mogged",
  ],
  brainrot: [
    "skibidi",
    "toilet",
    "gyatt",
    "gyat",
    "rizz",
    "rizzler",
    "fanum",
    "tax",
    "sus",
    "sussy",
    "baka",
    "amogus",
    "among us",
    "impostor",
    "vent",
    "drip",
    "sheesh",
    "bussin",
    "no cap",
    "cap",
    "bet",
    "periodt",
    "slay",
    "ate",
    "left no crumbs",
    "skull emoji",
    "crying laughing",
    "fr fr",
    "nah bro",
    "bro what",
    "lowkey",
    "highkey",
    "mid",
    "fire",
    "slaps",
    "hits different",
    "vibe check",
    "main character",
    "side character",
    "npc",
    "touch grass",
    "go outside",
    "chronically online",
    "terminally online",
    "grass",
    "maidenless",
    "no bitches",
    "bitches",
    "copium",
    "hopium",
    "cope",
    "seethe",
    "mald",
    "malding",
    "bozo",
    "clown",
    "skill issue",
    "get good",
    "git gud",
    "ez",
    "easy",
    "diff",
    "better",
    "inferior",
    "superior",
    "built different",
    "built wrong",
    "caught in 4k",
    "4k",
    "ratio + L",
    "yb better",
    "youngboy",
    "carti",
    "playboi",
    "opium",
    "vamp",
    "narcist",
    "wlr",
    "die lit",
    "travis scott",
    "astroworld",
    "sicko mode",
    "goosebumps",
    "kanye",
    "ye",
    "donda",
    "yeezus",
    "pablo",
    "tlop",
    "graduation",
    "808s",
    "heartbreak",
    "college dropout",
    "late registration",
    "mbdtf",
    "jik",
    "ksg",
    "wtt",
    "cruel summer",
    "good music",
    "yeezy",
    "boost",
    "foam runner",
    "slide",
    "700",
    "350",
    "500",
    "380",
    "450",
    "qntm",
    "bsktbl",
    "knit rnr",
    "nsltd",
    "basketball",
    "desert boot",
    "military boot",
    "combat boot",
    "chelsea boot",
    "sock shoe",
    "runner",
    "basketball shoe",
    "lifestyle shoe",
    "casual shoe",
    "sneaker",
    "shoe",
    "footwear",
    "adidas",
    "nike",
    "jordan",
    "air jordan",
    "air max",
    "air force",
    "dunk",
    "blazer",
    "cortez",
    "huarache",
    "presto",
    "react",
    "zoom",
    "free",
    "flex",
    "revolution",
    "downshifter",
    "tanjun",
    "benassi",
    "kawa",
    "sunray",
    "sandal",
    "slide",
    "flip flop",
    "slipper",
    "boot",
    "hiking boot",
    "work boot",
    "rain boot",
    "snow boot",
    "winter boot",
    "summer shoe",
    "spring shoe",
    "fall shoe",
    "autumn shoe",
    "seasonal shoe",
    "weather shoe",
    "outdoor shoe",
    "indoor shoe",
    "house shoe",
    "gym shoe",
    "running shoe",
    "walking shoe",
    "training shoe",
    "cross training",
    "weightlifting",
    "powerlifting",
    "bodybuilding",
    "fitness",
    "workout",
    "exercise",
    "cardio",
    "strength",
    "muscle",
    "gains",
    "bulk",
    "cut",
    "lean",
    "shredded",
    "ripped",
    "jacked",
    "swole",
    "buff",
    "fit",
    "athletic",
    "sports",
    "competition",
    "tournament",
    "championship",
    "league",
    "team",
    "squad",
    "crew",
    "gang",
    "clique",
    "group",
    "friend group",
    "squad goals",
    "friendship goals",
    "bestie",
    "bff",
    "ride or die",
    "day one",
    "og",
    "original",
    "real one",
    "fake friend",
    "snake",
    "two faced",
    "backstabber",
    "drama",
    "tea",
    "spill the tea",
    "gossip",
    "rumors",
    "he said she said",
    "beef",
    "feud",
    "conflict",
    "argument",
    "fight",
    "disagreement",
    "misunderstanding",
    "confusion",
    "miscommunication",
    "mixed signals",
    "red flag",
    "green flag",
    "yellow flag",
    "orange flag",
    "flag",
    "warning sign",
    "good sign",
    "bad sign",
    "toxic",
    "healthy",
    "unhealthy",
    "relationship",
    "dating",
    "talking",
    "situationship",
    "fwb",
    "friends with benefits",
    "no strings attached",
    "casual",
    "serious",
    "committed",
    "exclusive",
    "open relationship",
    "polyamory",
    "monogamy",
    "cheating",
    "unfaithful",
    "loyal",
    "faithful",
    "trust",
    "honesty",
    "communication",
    "respect",
    "boundaries",
    "consent",
    "safe",
    "unsafe",
    "comfortable",
    "uncomfortable",
    "awkward",
    "weird",
    "strange",
    "odd",
    "unusual",
    "normal",
    "typical",
    "common",
    "rare",
    "unique",
    "special",
    "different",
    "same",
    "similar",
    "identical",
    "opposite",
    "contrasting",
    "comparing",
    "comparison",
    "contrast",
    "difference",
    "similarity",
    "resemblance",
    "likeness",
    "parallel",
    "analogy",
    "metaphor",
    "simile",
    "figurative",
    "literal",
    "sarcastic",
    "ironic",
    "satirical",
    "humorous",
    "funny",
    "hilarious",
    "comedy",
    "joke",
    "pun",
    "wordplay",
    "wit",
    "clever",
    "smart",
    "intelligent",
    "genius",
    "brilliant",
    "wise",
    "knowledgeable",
    "educated",
    "learned",
    "scholarly",
    "academic",
    "intellectual",
    "thoughtful",
    "philosophical",
    "deep",
    "profound",
    "meaningful",
    "significant",
    "important",
    "relevant",
    "irrelevant",
    "pointless",
    "useless",
    "worthless",
    "valuable",
    "precious",
    "priceless",
    "expensive",
    "cheap",
    "affordable",
    "free",
    "costly",
    "budget",
    "money",
    "cash",
    "broke",
    "rich",
    "wealthy",
    "poor",
    "middle class",
    "upper class",
    "lower class",
    "working class",
    "blue collar",
    "white collar",
    "job",
    "work",
    "career",
    "profession",
    "occupation",
    "employment",
    "unemployed",
    "jobless",
    "fired",
    "laid off",
    "quit",
    "resigned",
    "retired",
    "promotion",
    "raise",
    "bonus",
    "salary",
    "wage",
    "hourly",
    "part time",
    "full time",
    "overtime",
    "shift",
    "schedule",
    "deadline",
    "project",
    "task",
    "assignment",
    "homework",
    "school",
    "college",
    "university",
    "high school",
    "middle school",
    "elementary",
    "kindergarten",
    "preschool",
    "daycare",
    "education",
    "learning",
    "studying",
    "test",
    "exam",
    "quiz",
    "grade",
    "gpa",
    "transcript",
    "diploma",
    "degree",
    "major",
    "minor",
    "concentration",
    "specialization",
    "field",
    "subject",
    "course",
    "class",
    "lecture",
    "seminar",
    "workshop",
    "lab",
    "laboratory",
    "experiment",
    "research",
    "study",
    "investigation",
    "analysis",
    "data",
    "statistics",
    "math",
    "science",
    "english",
    "history",
    "social studies",
    "geography",
    "art",
    "music",
    "physical education",
    "gym",
    "sports",
    "athletics",
    "extracurricular",
    "club",
    "organization",
    "student government",
    "student council",
    "prom",
    "homecoming",
    "dance",
    "formal",
    "semi formal",
    "casual",
    "dress code",
    "uniform",
    "dress",
    "suit",
    "tie",
    "bow tie",
    "tuxedo",
    "gown",
    "dress shirt",
    "blouse",
    "top",
    "shirt",
    "t shirt",
    "tank top",
    "crop top",
    "hoodie",
    "sweatshirt",
    "sweater",
    "cardigan",
    "jacket",
    "coat",
    "blazer",
    "vest",
    "pants",
    "jeans",
    "shorts",
    "skirt",
    "leggings",
    "tights",
    "underwear",
    "bra",
    "panties",
    "boxers",
    "briefs",
    "socks",
    "shoes",
    "sneakers",
    "boots",
    "sandals",
    "heels",
    "flats",
    "accessories",
    "jewelry",
    "necklace",
    "bracelet",
    "earrings",
    "ring",
    "watch",
    "hat",
    "cap",
    "beanie",
    "scarf",
    "gloves",
    "mittens",
    "belt",
    "bag",
    "purse",
    "backpack",
    "wallet",
    "phone",
    "smartphone",
    "iphone",
    "android",
    "samsung",
    "apple",
    "google",
    "technology",
    "tech",
    "gadget",
    "device",
    "computer",
    "laptop",
    "desktop",
    "tablet",
    "ipad",
    "kindle",
    "ereader",
    "gaming",
    "video games",
    "console",
    "playstation",
    "xbox",
    "nintendo",
    "switch",
    "pc gaming",
    "steam",
    "epic games",
    "fortnite",
    "minecraft",
    "roblox",
    "among us",
    "fall guys",
    "valorant",
    "league of legends",
    "overwatch",
    "call of duty",
    "battlefield",
    "fifa",
    "madden",
    "nba 2k",
    "gta",
    "red dead",
    "cyberpunk",
    "witcher",
    "skyrim",
    "fallout",
    "halo",
    "destiny",
    "apex legends",
    "warzone",
    "pubg",
    "rocket league",
    "rainbow six",
    "csgo",
    "counter strike",
    "dota",
    "starcraft",
    "world of warcraft",
    "wow",
    "final fantasy",
    "pokemon",
    "zelda",
    "mario",
    "sonic",
    "street fighter",
    "mortal kombat",
    "smash bros",
    "tekken",
    "dragon ball",
    "naruto",
    "one piece",
    "attack on titan",
    "demon slayer",
    "jujutsu kaisen",
    "my hero academia",
    "death note",
    "fullmetal alchemist",
    "hunter x hunter",
    "bleach",
    "one punch man",
    "mob psycho",
    "tokyo ghoul",
    "parasyte",
    "akira",
    "ghost in the shell",
    "cowboy bebop",
    "evangelion",
    "spirited away",
    "studio ghibli",
    "miyazaki",
    "anime",
    "manga",
    "weeb",
    "otaku",
    "kawaii",
    "senpai",
    "kouhai",
    "chan",
    "kun",
    "san",
    "sama",
    "dono",
    "sensei",
    "japanese",
    "japan",
    "korean",
    "korea",
    "kpop",
    "kdrama",
    "bts",
    "blackpink",
    "twice",
    "red velvet",
    "girls generation",
    "super junior",
    "exo",
    "seventeen",
    "stray kids",
    "itzy",
    "ive",
    "newjeans",
    "le sserafim",
    "aespa",
    "gidle",
    "mamamoo",
    "apink",
    "oh my girl",
    "weeekly",
    "fromis_9",
    "izone",
    "iz*one",
    "loona",
    "everglow",
    "dreamcatcher",
    "clc",
    "kard",
    "momoland",
    "pristin",
    "ioi",
    "produce 101",
    "produce 48",
    "produce x 101",
    "boys planet",
    "girls planet",
    "queendom",
    "kingdom",
    "road to kingdom",
    "show me the money",
    "unpretty rapstar",
    "high school rapper",
    "school rapper",
    "mix nine",
    "yg treasure box",
    "treasure",
    "ikon",
    "winner",
    "blackpink",
    "2ne1",
    "big bang",
    "psy",
    "gangnam style",
    "gentleman",
    "daddy",
    "new face",
    "i luv it",
    "right now",
    "hangover",
    "that that",
    "suga",
    "agust d",
    "rm",
    "jin",
    "jimin",
    "v",
    "jungkook",
    "j-hope",
    "jhope",
    "namjoon",
    "yoongi",
    "hoseok",
    "seokjin",
    "taehyung",
    "jeon jungkook",
    "kim namjoon",
    "min yoongi",
    "jung hoseok",
    "kim seokjin",
    "park jimin",
    "kim taehyung",
    "dynamite",
    "butter",
    "permission to dance",
    "life goes on",
    "be",
    "map of the soul",
    "love yourself",
    "wings",
    "dark and wild",
    "skool luv affair",
    "o!rul8,2?",
    "2 cool 4 skool",
    "face yourself",
    "wake up",
    "youth",
    "the most beautiful moment in life",
    "hyyh",
    "young forever",
    "persona",
    "shadow",
    "ego",
    "proof",
    "anthology",
    "yet to come",
    "run bts",
    "bts run",
    "bon voyage",
    "in the soop",
    "break the silence",
    "bring the soul",
    "love yourself world tour",
    "speak yourself",
    "map of the soul tour",
    "permission to dance on stage",
    "grammy",
    "billboard",
    "ama",
    "bbma",
    "mama",
    "mma",
    "gda",
    "sma",
    "kca",
    "tca",
    "pca",
    "mtv",
    "vma",
    "ema",
    "late night",
    "talk show",
    "variety show",
    "reality show",
    "tv show",
    "drama",
    "movie",
    "film",
    "netflix",
    "disney plus",
    "hulu",
    "amazon prime",
    "hbo max",
    "paramount plus",
    "apple tv",
    "youtube",
    "tiktok",
    "instagram",
    "twitter",
    "snapchat",
    "facebook",
    "pinterest",
    "tumblr",
    "reddit",
    "discord",
    "twitch",
    "youtube shorts",
    "reels",
    "stories",
    "live",
    "stream",
    "streaming",
    "streamer",
    "content creator",
    "influencer",
    "youtuber",
    "tiktoker",
    "instagrammer",
    "blogger",
    "vlogger",
    "podcast",
    "podcaster",
    "social media",
    "viral",
    "trending",
    "algorithm",
    "for you page",
    "fyp",
    "explore page",
    "discover",
    "recommended",
    "suggested",
    "follow",
    "unfollow",
    "like",
    "unlike",
    "share",
    "comment",
    "reply",
    "mention",
    "tag",
    "hashtag",
    "caption",
    "bio",
    "profile",
    "pfp",
    "profile picture",
    "avatar",
    "username",
    "handle",
    "dm",
    "direct message",
    "private message",
    "pm",
    "group chat",
    "gc",
    "story",
    "highlight",
    "saved",
    "archive",
    "close friends",
    "public",
    "private",
    "verified",
    "blue checkmark",
    "follower",
    "following",
    "mutual",
    "friend",
    "friendship",
    "relationship",
    "family",
    "sibling",
    "parent",
    "mom",
    "dad",
    "mother",
    "father",
    "son",
    "daughter",
    "brother",
    "sister",
    "cousin",
    "aunt",
    "uncle",
    "grandparent",
    "grandma",
    "grandpa",
    "grandmother",
    "grandfather",
    "niece",
    "nephew",
    "family reunion",
    "thanksgiving",
    "christmas",
    "holiday",
    "birthday",
    "anniversary",
    "graduation",
    "wedding",
    "funeral",
    "celebration",
    "party",
    "get together",
    "hangout",
    "sleepover",
    "movie night",
    "game night",
    "study session",
    "group project",
    "homework",
    "assignment",
    "essay",
    "report",
    "presentation",
    "speech",
    "debate",
    "discussion",
    "meeting",
    "conference",
    "seminar",
    "workshop",
    "training",
    "course",
    "class",
    "lesson",
    "tutorial",
    "guide",
    "instruction",
    "manual",
    "handbook",
    "textbook",
    "workbook",
    "notebook",
    "journal",
    "diary",
    "planner",
    "calendar",
    "schedule",
    "agenda",
    "to do list",
    "task",
    "chore",
    "responsibility",
    "duty",
    "obligation",
    "commitment",
    "promise",
    "goal",
    "objective",
    "target",
    "aim",
    "purpose",
    "mission",
    "vision",
    "dream",
    "aspiration",
    "ambition",
    "hope",
    "wish",
    "desire",
    "want",
    "need",
    "requirement",
    "necessity",
    "essential",
    "important",
    "crucial",
    "critical",
    "vital",
    "significant",
    "meaningful",
    "valuable",
    "precious",
    "special",
    "unique",
    "rare",
    "uncommon",
    "unusual",
    "extraordinary",
    "remarkable",
    "amazing",
    "incredible",
    "unbelievable",
    "fantastic",
    "wonderful",
    "awesome",
    "great",
    "excellent",
    "outstanding",
    "exceptional",
    "superb",
    "magnificent",
    "marvelous",
    "spectacular",
    "stunning",
    "breathtaking",
    "jaw dropping",
    "mind blowing",
    "awe inspiring",
    "impressive",
    "inspiring",
    "motivational",
    "encouraging",
    "uplifting",
    "positive",
    "optimistic",
    "hopeful",
    "confident",
    "determined",
    "persistent",
    "resilient",
    "strong",
    "tough",
    "brave",
    "courageous",
    "fearless",
    "bold",
    "daring",
    "adventurous",
    "spontaneous",
    "impulsive",
    "reckless",
    "careless",
    "thoughtless",
    "mindless",
    "senseless",
    "foolish",
    "silly",
    "ridiculous",
    "absurd",
    "nonsensical",
    "illogical",
    "irrational",
    "unreasonable",
    "unfair",
    "unjust",
    "wrong",
    "incorrect",
    "mistaken",
    "false",
    "untrue",
    "dishonest",
    "deceptive",
    "misleading",
    "lying",
    "fake",
    "phony",
    "artificial",
    "synthetic",
    "man made",
    "manufactured",
    "processed",
    "natural",
    "organic",
    "pure",
    "clean",
    "fresh",
    "new",
    "recent",
    "latest",
    "current",
    "present",
    "modern",
    "contemporary",
    "up to date",
    "trendy",
    "fashionable",
    "stylish",
    "chic",
    "cool",
    "hip",
    "in",
    "popular",
    "mainstream",
    "underground",
    "alternative",
    "indie",
    "independent",
    "DIY",
    "do it yourself",
    "homemade",
    "handmade",
    "crafted",
    "artisan",
    "artistic",
    "creative",
    "imaginative",
    "innovative",
    "original",
    "unique",
    "one of a kind",
    "custom",
    "personalized",
    "individual",
    "personal",
    "private",
    "intimate",
    "close",
    "tight",
    "strong",
    "solid",
    "stable",
    "secure",
    "safe",
    "protected",
    "defended",
    "guarded",
    "watched",
    "monitored",
    "observed",
    "noticed",
    "seen",
    "spotted",
    "caught",
    "found",
    "discovered",
    "uncovered",
    "revealed",
    "exposed",
    "shown",
    "displayed",
    "presented",
    "demonstrated",
    "illustrated",
    "explained",
    "described",
    "detailed",
    "outlined",
    "summarized",
    "abbreviated",
    "shortened",
    "reduced",
    "minimized",
    "decreased",
    "lowered",
    "dropped",
    "fell",
    "declined",
    "went down",
    "plummeted",
    "crashed",
    "collapsed",
    "failed",
    "broke",
    "stopped",
    "ended",
    "finished",
    "completed",
    "done",
    "over",
    "past",
    "previous",
    "former",
    "old",
    "ancient",
    "vintage",
    "retro",
    "classic",
    "traditional",
    "conventional",
    "standard",
    "normal",
    "regular",
    "ordinary",
    "common",
    "typical",
    "usual",
    "expected",
    "predictable",
    "routine",
    "boring",
    "dull",
    "monotonous",
    "repetitive",
    "same",
    "identical",
    "duplicate",
    "copy",
    "replica",
    "imitation",
    "fake",
    "counterfeit",
    "fraud",
    "scam",
    "trick",
    "prank",
    "joke",
    "humor",
    "comedy",
    "funny",
    "hilarious",
    "amusing",
    "entertaining",
    "enjoyable",
    "fun",
    "exciting",
    "thrilling",
    "exhilarating",
    "stimulating",
    "energizing",
    "invigorating",
    "refreshing",
    "rejuvenating",
    "relaxing",
    "calming",
    "soothing",
    "peaceful",
    "tranquil",
    "serene",
    "quiet",
    "silent",
    "still",
    "motionless",
    "stationary",
    "fixed",
    "stuck",
    "trapped",
    "confined",
    "restricted",
    "limited",
    "constrained",
    "bound",
    "tied",
    "connected",
    "linked",
    "attached",
    "joined",
    "united",
    "combined",
    "merged",
    "blended",
    "mixed",
    "stirred",
    "shaken",
    "moved",
    "shifted",
    "changed",
    "altered",
    "modified",
    "adjusted",
    "adapted",
    "evolved",
    "developed",
    "grew",
    "expanded",
    "enlarged",
    "increased",
    "boosted",
    "enhanced",
    "improved",
    "upgraded",
    "updated",
    "revised",
    "edited",
    "corrected",
    "fixed",
    "repaired",
    "restored",
    "recovered",
    "healed",
    "cured",
    "treated",
    "helped",
    "assisted",
    "supported",
    "backed",
    "encouraged",
    "motivated",
    "inspired",
    "influenced",
    "affected",
    "impacted",
    "changed",
    "transformed",
    "converted",
    "switched",
    "swapped",
    "exchanged",
    "traded",
    "replaced",
    "substituted",
    "filled in",
    "covered",
    "protected",
    "shielded",
    "defended",
    "fought",
    "battled",
    "struggled",
    "competed",
    "challenged",
    "tested",
    "tried",
    "attempted",
    "effort",
    "work",
    "labor",
    "job",
    "task",
    "duty",
    "responsibility",
    "role",
    "position",
    "rank",
    "status",
    "level",
    "grade",
    "class",
    "category",
    "type",
    "kind",
    "sort",
    "variety",
    "version",
    "edition",
    "model",
    "brand",
    "make",
    "manufacturer",
    "company",
  ],
};

function detectThemes(text: string): string[] {
  const lowerText = text.toLowerCase();
  const detectedThemes: string[] = [];

  for (const [theme, keywords] of Object.entries(THEME_KEYWORDS)) {
    if (keywords.some((keyword) => lowerText.includes(keyword))) {
      detectedThemes.push(theme);
    }
  }

  return detectedThemes.length > 0 ? detectedThemes : ["random"];
}

function saveToDatabase(submissionData: any) {
  const dbPath = path.join(process.cwd(), "approved_submissions.json");
  let database = [];

  try {
    if (fs.existsSync(dbPath)) {
      const fileContent = fs.readFileSync(dbPath, "utf8");
      if (fileContent.trim().length > 0) {
        database = JSON.parse(fileContent);
      }
    }
  } catch (error) {
    console.error("Error reading database:", error);
  }

  database.push(submissionData);

  try {
    fs.writeFileSync(dbPath, JSON.stringify(database, null, 2));
    console.log("✅ Submission saved to database");
  } catch (error) {
    console.error("❌ Error writing to database:", error);
  }
}

export const Submit: Command = {
  name: "submit",
  description: "Send a private submission for admin review",
  run: async (client: Client, interaction: CommandInteraction) => {
    console.log("🔔 /submit command triggered by", interaction.user.tag);

    await interaction.reply({
      content: "📩 Check your DMs to complete your submission!",
      flags: MessageFlags.Ephemeral,
    });

    try {
      const dm = await interaction.user.send(
        "📝 Please submit your **What Would You Do?** reply here within 60 seconds.",
      );

      console.log("⌛ Waiting for DM from:", interaction.user.tag);

      const collected = await (dm.channel as DMChannel).awaitMessages({
        filter: (m) => m.author.id === interaction.user.id,
        max: 1,
        time: 60000,
        errors: ["time"],
      });

      const submission = collected.first()?.content;

      if (!submission) throw new Error("No message received.");

      await interaction.user.send("✅ Thank you for your submission!");

      // Log submission to file
      const logData = {
        timestamp: new Date().toISOString(),
        userId: interaction.user.id,
        username: interaction.user.username,
        submission,
      };

      const logFilePath = path.join(process.cwd(), "userwwydprompts.json");
      let existingData = [];

      try {
        if (fs.existsSync(logFilePath)) {
          const fileContent = fs.readFileSync(logFilePath, "utf8");
          if (fileContent.trim().length > 0)
            existingData = JSON.parse(fileContent);
          else existingData = [];
        }
      } catch (error) {
        console.error("📂 Error reading log file:", error);
      }

      existingData.push(logData);

      try {
        fs.writeFileSync(logFilePath, JSON.stringify(existingData, null, 2));
        console.log("📁 Submission saved to log file");
      } catch (error) {
        console.error("❌ Error writing to log file:", error);
      }

      // Forward to admin channel with approval buttons
      const adminChannel = await client.channels.fetch(ADMIN_CHANNEL_ID);
      if (adminChannel && adminChannel.isTextBased()) {
        const approveButton = new ButtonBuilder()
          .setCustomId(`approve_${interaction.user.id}_${Date.now()}`)
          .setLabel("✅ Approve")
          .setStyle(ButtonStyle.Success);

        const rejectButton = new ButtonBuilder()
          .setCustomId(`reject_${interaction.user.id}_${Date.now()}`)
          .setLabel("❌ Reject")
          .setStyle(ButtonStyle.Danger);

        const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
          approveButton,
          rejectButton,
        );

        const themes = detectThemes(submission);
        const themeText =
          themes.length > 0
            ? `\n🏷️ **Detected themes:** ${themes.join(", ")}`
            : "";

        const message = await (adminChannel as TextChannel).send({
          content: `📨 **New submission from <@${interaction.user.id}>:**\n\`\`\`${submission}\`\`\`${themeText}`,
          components: [row],
        });

        // Handle button interactions
        const filter = (i: any) =>
          i.isButton() &&
          (i.customId.startsWith("approve_") ||
            i.customId.startsWith("reject_"));

        const collector = message.createMessageComponentCollector({
          filter,
          time: 24 * 60 * 60 * 1000, // 24 hours
        });

        collector.on("collect", async (i: ButtonInteraction) => {
          if (!i.memberPermissions?.has("Administrator")) {
            await i.reply({
              content: "❌ You don't have permission to review submissions.",
              ephemeral: true,
            });
            return;
          }

          const isApproved = i.customId.startsWith("approve_");

          if (isApproved) {
            // Save to database with theme tags
            const dbData = {
              id: Date.now().toString(),
              timestamp: new Date().toISOString(),
              userId: interaction.user.id,
              username: interaction.user.username,
              submission: submission,
              themes: themes,
              approvedBy: i.user.id,
              approvedAt: new Date().toISOString(),
            };

            saveToDatabase(dbData);

            await i.update({
              content: `✅ **APPROVED** by <@${i.user.id}>\n\n📨 **Submission from <@${interaction.user.id}>:**\n\`\`\`${submission}\`\`\`\n🏷️ **Themes:** ${themes.join(", ")}`,
              components: [],
            });

            // Notify the user
            try {
              await interaction.user.send(
                "🎉 Your submission has been approved and added to the database!",
              );
            } catch (error) {
              console.error("Could not DM user about approval:", error);
            }
          } else {
            await i.update({
              content: `❌ **REJECTED** by <@${i.user.id}>\n\n📨 **Submission from <@${interaction.user.id}>:**\n\`\`\`${submission}\`\`\`\n🏷️ **Themes:** ${themes.join(", ")}`,
              components: [],
            });

            // Notify the user
            try {
              await interaction.user.send(
                "😔 Your submission was not approved. Feel free to try again with a different response!",
              );
            } catch (error) {
              console.error("Could not DM user about rejection:", error);
            }
          }
        });

        collector.on("end", () => {
          // Disable buttons after timeout
          message
            .edit({
              components: [],
            })
            .catch(console.error);
        });
      }

      console.log("✅ Submission forwarded to admin channel");
    } catch (error: any) {
      console.error("❌ Error during submission:", error);

      if (error.code === "time") {
        await interaction.followUp({
          content: "⏰ You didn’t respond in time. Please try again.",
          flags: MessageFlags.Ephemeral,
        });
      } else {
        await interaction.followUp({
          content: "❌ Something went wrong while collecting your message.",
          flags: MessageFlags.Ephemeral,
        });
      }
    }
  },
};
